config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'spots#index'

  resources :spots do
    resources :photos, only: [:new, :create]
  end

  get "/browse" => "spots#browse"
  post "/browse" => "spots#browse"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :spot

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  validates :location, :presence => true
  validates :header, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
  validates :details, :presence => true
  validates :availability, :presence => true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/spots.rb
class Spot < ActiveRecord::Base
  belongs_to :user
  validates :location, :presence => true
  validates :heading, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
  validates :details, :presence => true
  validates :availability, :presence => true
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :spots

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.signup_confirmation(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @spot = Spot.find(params[:spot_id])
    @photo = Photo.new
  end

  def create
    @spot = Spot.find(params[:spot_id])
    @photo = @spot.photos.new(photo_params)
    if @photo.save
      redirect_to spots_path(@spot), :notice => "Print added!"
    else
      render :new, :notice => "Try again!"
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:photo)
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @spots = Spot.all
  end

  def browse
    @spots = Spot.all
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def create
    @spot = Spot.new(spots_params)
    if @spot.save
      redirect_to spots_path, notice: "Spot has been successfully listed!"
    else
      render :new
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path, notice: "Spot removed from inventory"
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spots_params)
      redirect_to spots_path(@spot), notice: "Spot edit complete"
    else
      render :edit
    end
  end

  private
  def spots_params
    params.require(:spot).permit(:photo, :location, :header, :description, :price, :details, :images, :availability, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to users_path, notice: "Signed up successfully."
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private
  def users_params
    params.require(:user).permit(:name, :email, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>

  <div class="container">
    <div class="row">
      <div id="site-title" class="col-md-6 left">
        <%= link_to "is The New Timeshare", '/' %>
      </div>
      <div class="navbar col-md-6 right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>

    <div class="row">
        <p>
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </p>
        <%= yield %>
    </div>

  </div>
</body>
<footer>
  <div class="container">
    <p><%= link_to "Return to Homepage", spots_path %></p>
  </div>
</footer>
</html>

app/views/photos/new.html.erb
<h4>Prints</h4>
  <%= form_for [@spot, @photo], :html => { :multipart => true} do |f| %>
    <ul class="formList list-unstyled well">
      <li>
        <%= f.label :photo %>
        <%= f.file_field :photo %>
      </li>

      <li class="submit">
        <%= f.submit "Add Image", :class => "btn btn-primary" %>
      </li>
    </ul>
  <% end %>

app/views/spots/_form.html.erb
<%= render "layouts/errors", :object => @spot %>

<%= form_for [@spot] do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :header %>
  <%= f.text_field :header %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.label :availability %>
  <%= f.text_field :availability %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit %>
<% end %>

app/views/spots/browse.html.erb
<h1>Browse Spots</h1>

<% if Spot.all.any? %>
<% @spots.each do |spot| %>
<li><%= link_to spot.header, spot_path(spot) %></li>
<% end %>
<% end %>

app/views/spots/edit.html.erb
<% content_for(:title, "Welcome! | iTNT")%>
<h1>Edit Your Spot!</h1>

<%= render 'form' %>

<h1>Your Spots</h1>

<% if @user.spots.any? %>

<ul>
  <% @user.spots.each do |spot| %>
  <li>
    <%= link_to spot.header, spot_path(spot) %>
    <%= link_to "Edit", edit_spot_path(@user, spot) %> |
    <%= link_to "Delete", spot_path(@user, spot),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %>
    </li>
    <% end %>

  </ul>
  <% end %>

app/views/spots/index.html.erb
<% content_for(:title, "Welcome! | iTNT")%>

<h3>Totally Rad search by location bar here!</h3>
  <p>
    which will list all spots with location
  </p>
  <%= link_to "Browse the Spots", browse_path %>
  <%= link_to "List your Spot", new_spot_path(:user_id) %>

app/views/spots/new.html.erb
<% content_for(:title, "Welcome! | iTNT")%>
<h1>Create a new Spot!</h1>

<%= render 'form' %>

app/views/spots/show.html.erb
<% content_for(:title, "Welcome! | iTNT")%>
<h1><%= @spot.header %></h1>

<%= image_tag @spot.photo.url(:medium) %>

<p>
  <%= @spot.description %>
</p>

  <ul>
    <li><%= @spot.details %></li>
    <li>$<%= @spot.price %></li>
    <li><%= @spot.location %></li>
    <li><%= @spot.availability %></li>
  </ul>


<p><%= link_to "Edit", edit_spot_path(@spot) %></p>
<p><%= link_to "Delete", spot_path(@spot), :data => { :confirm => "Are you sure?",
                                           :method => "delete" } %></p>

app/views/users/index.html.erb
<h1>is The New Timeshare</h1>

<h3>Totally Rad search by location bar here!</h3>
<p>
  which will list all spots with location
</p>

<%= link_to "List your spot!", new_spot_path(@user) %>
<p>
  add a spot form
  which will render user spot listings
</p>